evidence: hw2.c hw2_evidence.c
	gcc -Wall -o hw2_evidence hw2.c hw2_evidence.c

sumcubes: hw2.c sumcubes.c
	gcc -Wall -o sumcubes hw2.c sumcubes.c

ladder: hw2.c ladder.c
	gcc -Wall -o ladder hw2.c ladder.c

stairs: hw2.c stairs.c
	gcc -Wall -o stairs hw2.c stairs.c

basetodecimal: hw2.c basetodecimal.c
	gcc -Wall -o basetodecimal hw2.c basetodecimal.c
